// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cassandra.proto

package cassandra

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RequestParameter_Consistency int32

const (
	RequestParameter_ONE    RequestParameter_Consistency = 0
	RequestParameter_QUORUM RequestParameter_Consistency = 1
)

var RequestParameter_Consistency_name = map[int32]string{
	0: "ONE",
	1: "QUORUM",
}

var RequestParameter_Consistency_value = map[string]int32{
	"ONE":    0,
	"QUORUM": 1,
}

func (x RequestParameter_Consistency) String() string {
	return proto.EnumName(RequestParameter_Consistency_name, int32(x))
}

func (RequestParameter_Consistency) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_32c4df2e0eaa2354, []int{1, 0}
}

type ClientRead_Consistency int32

const (
	ClientRead_ONE    ClientRead_Consistency = 0
	ClientRead_QUORUM ClientRead_Consistency = 1
)

var ClientRead_Consistency_name = map[int32]string{
	0: "ONE",
	1: "QUORUM",
}

var ClientRead_Consistency_value = map[string]int32{
	"ONE":    0,
	"QUORUM": 1,
}

func (x ClientRead_Consistency) String() string {
	return proto.EnumName(ClientRead_Consistency_name, int32(x))
}

func (ClientRead_Consistency) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_32c4df2e0eaa2354, []int{3, 0}
}

type InitReplicaCluster struct {
	AllReplica           []*InitReplicaCluster_Replica `protobuf:"bytes,1,rep,name=all_replica,json=allReplica,proto3" json:"all_replica,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *InitReplicaCluster) Reset()         { *m = InitReplicaCluster{} }
func (m *InitReplicaCluster) String() string { return proto.CompactTextString(m) }
func (*InitReplicaCluster) ProtoMessage()    {}
func (*InitReplicaCluster) Descriptor() ([]byte, []int) {
	return fileDescriptor_32c4df2e0eaa2354, []int{0}
}

func (m *InitReplicaCluster) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitReplicaCluster.Unmarshal(m, b)
}
func (m *InitReplicaCluster) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitReplicaCluster.Marshal(b, m, deterministic)
}
func (m *InitReplicaCluster) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitReplicaCluster.Merge(m, src)
}
func (m *InitReplicaCluster) XXX_Size() int {
	return xxx_messageInfo_InitReplicaCluster.Size(m)
}
func (m *InitReplicaCluster) XXX_DiscardUnknown() {
	xxx_messageInfo_InitReplicaCluster.DiscardUnknown(m)
}

var xxx_messageInfo_InitReplicaCluster proto.InternalMessageInfo

func (m *InitReplicaCluster) GetAllReplica() []*InitReplicaCluster_Replica {
	if m != nil {
		return m.AllReplica
	}
	return nil
}

type InitReplicaCluster_Replica struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Ip                   string   `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Port                 string   `protobuf:"bytes,3,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitReplicaCluster_Replica) Reset()         { *m = InitReplicaCluster_Replica{} }
func (m *InitReplicaCluster_Replica) String() string { return proto.CompactTextString(m) }
func (*InitReplicaCluster_Replica) ProtoMessage()    {}
func (*InitReplicaCluster_Replica) Descriptor() ([]byte, []int) {
	return fileDescriptor_32c4df2e0eaa2354, []int{0, 0}
}

func (m *InitReplicaCluster_Replica) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitReplicaCluster_Replica.Unmarshal(m, b)
}
func (m *InitReplicaCluster_Replica) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitReplicaCluster_Replica.Marshal(b, m, deterministic)
}
func (m *InitReplicaCluster_Replica) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitReplicaCluster_Replica.Merge(m, src)
}
func (m *InitReplicaCluster_Replica) XXX_Size() int {
	return xxx_messageInfo_InitReplicaCluster_Replica.Size(m)
}
func (m *InitReplicaCluster_Replica) XXX_DiscardUnknown() {
	xxx_messageInfo_InitReplicaCluster_Replica.DiscardUnknown(m)
}

var xxx_messageInfo_InitReplicaCluster_Replica proto.InternalMessageInfo

func (m *InitReplicaCluster_Replica) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *InitReplicaCluster_Replica) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *InitReplicaCluster_Replica) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

type RequestParameter struct {
	OriginReplica        string                       `protobuf:"bytes,1,opt,name=originReplica,proto3" json:"originReplica,omitempty"`
	Key                  uint32                       `protobuf:"varint,2,opt,name=key,proto3" json:"key,omitempty"`
	Value                string                       `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Consistency          RequestParameter_Consistency `protobuf:"varint,4,opt,name=consistency,proto3,enum=RequestParameter_Consistency" json:"consistency,omitempty"`
	Timestamp            *timestamp.Timestamp         `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	TimeInSeconds        int64                        `protobuf:"varint,6,opt,name=timeInSeconds,proto3" json:"timeInSeconds,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *RequestParameter) Reset()         { *m = RequestParameter{} }
func (m *RequestParameter) String() string { return proto.CompactTextString(m) }
func (*RequestParameter) ProtoMessage()    {}
func (*RequestParameter) Descriptor() ([]byte, []int) {
	return fileDescriptor_32c4df2e0eaa2354, []int{1}
}

func (m *RequestParameter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestParameter.Unmarshal(m, b)
}
func (m *RequestParameter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestParameter.Marshal(b, m, deterministic)
}
func (m *RequestParameter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestParameter.Merge(m, src)
}
func (m *RequestParameter) XXX_Size() int {
	return xxx_messageInfo_RequestParameter.Size(m)
}
func (m *RequestParameter) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestParameter.DiscardUnknown(m)
}

var xxx_messageInfo_RequestParameter proto.InternalMessageInfo

func (m *RequestParameter) GetOriginReplica() string {
	if m != nil {
		return m.OriginReplica
	}
	return ""
}

func (m *RequestParameter) GetKey() uint32 {
	if m != nil {
		return m.Key
	}
	return 0
}

func (m *RequestParameter) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *RequestParameter) GetConsistency() RequestParameter_Consistency {
	if m != nil {
		return m.Consistency
	}
	return RequestParameter_ONE
}

func (m *RequestParameter) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *RequestParameter) GetTimeInSeconds() int64 {
	if m != nil {
		return m.TimeInSeconds
	}
	return 0
}

type Response struct {
	OriginReplica        string   `protobuf:"bytes,1,opt,name=originReplica,proto3" json:"originReplica,omitempty"`
	Key                  uint32   `protobuf:"varint,2,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Arrival              int64    `protobuf:"varint,4,opt,name=arrival,proto3" json:"arrival,omitempty"`
	Status               bool     `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	RespMessage          string   `protobuf:"bytes,6,opt,name=respMessage,proto3" json:"respMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_32c4df2e0eaa2354, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetOriginReplica() string {
	if m != nil {
		return m.OriginReplica
	}
	return ""
}

func (m *Response) GetKey() uint32 {
	if m != nil {
		return m.Key
	}
	return 0
}

func (m *Response) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Response) GetArrival() int64 {
	if m != nil {
		return m.Arrival
	}
	return 0
}

func (m *Response) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *Response) GetRespMessage() string {
	if m != nil {
		return m.RespMessage
	}
	return ""
}

type ClientRead struct {
	Key                  uint32                 `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"`
	Consistency          ClientRead_Consistency `protobuf:"varint,2,opt,name=consistency,proto3,enum=ClientRead_Consistency" json:"consistency,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ClientRead) Reset()         { *m = ClientRead{} }
func (m *ClientRead) String() string { return proto.CompactTextString(m) }
func (*ClientRead) ProtoMessage()    {}
func (*ClientRead) Descriptor() ([]byte, []int) {
	return fileDescriptor_32c4df2e0eaa2354, []int{3}
}

func (m *ClientRead) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientRead.Unmarshal(m, b)
}
func (m *ClientRead) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientRead.Marshal(b, m, deterministic)
}
func (m *ClientRead) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientRead.Merge(m, src)
}
func (m *ClientRead) XXX_Size() int {
	return xxx_messageInfo_ClientRead.Size(m)
}
func (m *ClientRead) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientRead.DiscardUnknown(m)
}

var xxx_messageInfo_ClientRead proto.InternalMessageInfo

func (m *ClientRead) GetKey() uint32 {
	if m != nil {
		return m.Key
	}
	return 0
}

func (m *ClientRead) GetConsistency() ClientRead_Consistency {
	if m != nil {
		return m.Consistency
	}
	return ClientRead_ONE
}

type ReplicaRead struct {
	Key                  uint32   `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReplicaRead) Reset()         { *m = ReplicaRead{} }
func (m *ReplicaRead) String() string { return proto.CompactTextString(m) }
func (*ReplicaRead) ProtoMessage()    {}
func (*ReplicaRead) Descriptor() ([]byte, []int) {
	return fileDescriptor_32c4df2e0eaa2354, []int{4}
}

func (m *ReplicaRead) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplicaRead.Unmarshal(m, b)
}
func (m *ReplicaRead) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplicaRead.Marshal(b, m, deterministic)
}
func (m *ReplicaRead) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplicaRead.Merge(m, src)
}
func (m *ReplicaRead) XXX_Size() int {
	return xxx_messageInfo_ReplicaRead.Size(m)
}
func (m *ReplicaRead) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplicaRead.DiscardUnknown(m)
}

var xxx_messageInfo_ReplicaRead proto.InternalMessageInfo

func (m *ReplicaRead) GetKey() uint32 {
	if m != nil {
		return m.Key
	}
	return 0
}

type ClientPut struct {
	Input                *RequestParameter `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ClientPut) Reset()         { *m = ClientPut{} }
func (m *ClientPut) String() string { return proto.CompactTextString(m) }
func (*ClientPut) ProtoMessage()    {}
func (*ClientPut) Descriptor() ([]byte, []int) {
	return fileDescriptor_32c4df2e0eaa2354, []int{5}
}

func (m *ClientPut) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientPut.Unmarshal(m, b)
}
func (m *ClientPut) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientPut.Marshal(b, m, deterministic)
}
func (m *ClientPut) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientPut.Merge(m, src)
}
func (m *ClientPut) XXX_Size() int {
	return xxx_messageInfo_ClientPut.Size(m)
}
func (m *ClientPut) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientPut.DiscardUnknown(m)
}

var xxx_messageInfo_ClientPut proto.InternalMessageInfo

func (m *ClientPut) GetInput() *RequestParameter {
	if m != nil {
		return m.Input
	}
	return nil
}

type ReplicaPut struct {
	Input                *RequestParameter `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ReplicaPut) Reset()         { *m = ReplicaPut{} }
func (m *ReplicaPut) String() string { return proto.CompactTextString(m) }
func (*ReplicaPut) ProtoMessage()    {}
func (*ReplicaPut) Descriptor() ([]byte, []int) {
	return fileDescriptor_32c4df2e0eaa2354, []int{6}
}

func (m *ReplicaPut) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplicaPut.Unmarshal(m, b)
}
func (m *ReplicaPut) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplicaPut.Marshal(b, m, deterministic)
}
func (m *ReplicaPut) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplicaPut.Merge(m, src)
}
func (m *ReplicaPut) XXX_Size() int {
	return xxx_messageInfo_ReplicaPut.Size(m)
}
func (m *ReplicaPut) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplicaPut.DiscardUnknown(m)
}

var xxx_messageInfo_ReplicaPut proto.InternalMessageInfo

func (m *ReplicaPut) GetInput() *RequestParameter {
	if m != nil {
		return m.Input
	}
	return nil
}

type InputRequest struct {
	// Types that are valid to be assigned to InputRequest:
	//	*InputRequest_InitReplica
	//	*InputRequest_ClientRead
	//	*InputRequest_ReplicaRead
	//	*InputRequest_ClientPut
	//	*InputRequest_ReplicaPut
	//	*InputRequest_Response
	InputRequest         isInputRequest_InputRequest `protobuf_oneof:"input_request"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *InputRequest) Reset()         { *m = InputRequest{} }
func (m *InputRequest) String() string { return proto.CompactTextString(m) }
func (*InputRequest) ProtoMessage()    {}
func (*InputRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_32c4df2e0eaa2354, []int{7}
}

func (m *InputRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InputRequest.Unmarshal(m, b)
}
func (m *InputRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InputRequest.Marshal(b, m, deterministic)
}
func (m *InputRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InputRequest.Merge(m, src)
}
func (m *InputRequest) XXX_Size() int {
	return xxx_messageInfo_InputRequest.Size(m)
}
func (m *InputRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InputRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InputRequest proto.InternalMessageInfo

type isInputRequest_InputRequest interface {
	isInputRequest_InputRequest()
}

type InputRequest_InitReplica struct {
	InitReplica *InitReplicaCluster `protobuf:"bytes,1,opt,name=init_replica,json=initReplica,proto3,oneof"`
}

type InputRequest_ClientRead struct {
	ClientRead *ClientRead `protobuf:"bytes,2,opt,name=client_read,json=clientRead,proto3,oneof"`
}

type InputRequest_ReplicaRead struct {
	ReplicaRead *ReplicaRead `protobuf:"bytes,3,opt,name=replica_read,json=replicaRead,proto3,oneof"`
}

type InputRequest_ClientPut struct {
	ClientPut *ClientPut `protobuf:"bytes,4,opt,name=client_put,json=clientPut,proto3,oneof"`
}

type InputRequest_ReplicaPut struct {
	ReplicaPut *ReplicaPut `protobuf:"bytes,5,opt,name=replica_put,json=replicaPut,proto3,oneof"`
}

type InputRequest_Response struct {
	Response *Response `protobuf:"bytes,6,opt,name=response,proto3,oneof"`
}

func (*InputRequest_InitReplica) isInputRequest_InputRequest() {}

func (*InputRequest_ClientRead) isInputRequest_InputRequest() {}

func (*InputRequest_ReplicaRead) isInputRequest_InputRequest() {}

func (*InputRequest_ClientPut) isInputRequest_InputRequest() {}

func (*InputRequest_ReplicaPut) isInputRequest_InputRequest() {}

func (*InputRequest_Response) isInputRequest_InputRequest() {}

func (m *InputRequest) GetInputRequest() isInputRequest_InputRequest {
	if m != nil {
		return m.InputRequest
	}
	return nil
}

func (m *InputRequest) GetInitReplica() *InitReplicaCluster {
	if x, ok := m.GetInputRequest().(*InputRequest_InitReplica); ok {
		return x.InitReplica
	}
	return nil
}

func (m *InputRequest) GetClientRead() *ClientRead {
	if x, ok := m.GetInputRequest().(*InputRequest_ClientRead); ok {
		return x.ClientRead
	}
	return nil
}

func (m *InputRequest) GetReplicaRead() *ReplicaRead {
	if x, ok := m.GetInputRequest().(*InputRequest_ReplicaRead); ok {
		return x.ReplicaRead
	}
	return nil
}

func (m *InputRequest) GetClientPut() *ClientPut {
	if x, ok := m.GetInputRequest().(*InputRequest_ClientPut); ok {
		return x.ClientPut
	}
	return nil
}

func (m *InputRequest) GetReplicaPut() *ReplicaPut {
	if x, ok := m.GetInputRequest().(*InputRequest_ReplicaPut); ok {
		return x.ReplicaPut
	}
	return nil
}

func (m *InputRequest) GetResponse() *Response {
	if x, ok := m.GetInputRequest().(*InputRequest_Response); ok {
		return x.Response
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*InputRequest) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _InputRequest_OneofMarshaler, _InputRequest_OneofUnmarshaler, _InputRequest_OneofSizer, []interface{}{
		(*InputRequest_InitReplica)(nil),
		(*InputRequest_ClientRead)(nil),
		(*InputRequest_ReplicaRead)(nil),
		(*InputRequest_ClientPut)(nil),
		(*InputRequest_ReplicaPut)(nil),
		(*InputRequest_Response)(nil),
	}
}

func _InputRequest_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*InputRequest)
	// input_request
	switch x := m.InputRequest.(type) {
	case *InputRequest_InitReplica:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.InitReplica); err != nil {
			return err
		}
	case *InputRequest_ClientRead:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ClientRead); err != nil {
			return err
		}
	case *InputRequest_ReplicaRead:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ReplicaRead); err != nil {
			return err
		}
	case *InputRequest_ClientPut:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ClientPut); err != nil {
			return err
		}
	case *InputRequest_ReplicaPut:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ReplicaPut); err != nil {
			return err
		}
	case *InputRequest_Response:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Response); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("InputRequest.InputRequest has unexpected type %T", x)
	}
	return nil
}

func _InputRequest_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*InputRequest)
	switch tag {
	case 1: // input_request.init_replica
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(InitReplicaCluster)
		err := b.DecodeMessage(msg)
		m.InputRequest = &InputRequest_InitReplica{msg}
		return true, err
	case 2: // input_request.client_read
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ClientRead)
		err := b.DecodeMessage(msg)
		m.InputRequest = &InputRequest_ClientRead{msg}
		return true, err
	case 3: // input_request.replica_read
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ReplicaRead)
		err := b.DecodeMessage(msg)
		m.InputRequest = &InputRequest_ReplicaRead{msg}
		return true, err
	case 4: // input_request.client_put
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ClientPut)
		err := b.DecodeMessage(msg)
		m.InputRequest = &InputRequest_ClientPut{msg}
		return true, err
	case 5: // input_request.replica_put
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ReplicaPut)
		err := b.DecodeMessage(msg)
		m.InputRequest = &InputRequest_ReplicaPut{msg}
		return true, err
	case 6: // input_request.response
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Response)
		err := b.DecodeMessage(msg)
		m.InputRequest = &InputRequest_Response{msg}
		return true, err
	default:
		return false, nil
	}
}

func _InputRequest_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*InputRequest)
	// input_request
	switch x := m.InputRequest.(type) {
	case *InputRequest_InitReplica:
		s := proto.Size(x.InitReplica)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *InputRequest_ClientRead:
		s := proto.Size(x.ClientRead)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *InputRequest_ReplicaRead:
		s := proto.Size(x.ReplicaRead)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *InputRequest_ClientPut:
		s := proto.Size(x.ClientPut)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *InputRequest_ReplicaPut:
		s := proto.Size(x.ReplicaPut)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *InputRequest_Response:
		s := proto.Size(x.Response)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterEnum("RequestParameter_Consistency", RequestParameter_Consistency_name, RequestParameter_Consistency_value)
	proto.RegisterEnum("ClientRead_Consistency", ClientRead_Consistency_name, ClientRead_Consistency_value)
	proto.RegisterType((*InitReplicaCluster)(nil), "InitReplicaCluster")
	proto.RegisterType((*InitReplicaCluster_Replica)(nil), "InitReplicaCluster.Replica")
	proto.RegisterType((*RequestParameter)(nil), "RequestParameter")
	proto.RegisterType((*Response)(nil), "Response")
	proto.RegisterType((*ClientRead)(nil), "ClientRead")
	proto.RegisterType((*ReplicaRead)(nil), "ReplicaRead")
	proto.RegisterType((*ClientPut)(nil), "ClientPut")
	proto.RegisterType((*ReplicaPut)(nil), "ReplicaPut")
	proto.RegisterType((*InputRequest)(nil), "InputRequest")
}

func init() { proto.RegisterFile("cassandra.proto", fileDescriptor_32c4df2e0eaa2354) }

var fileDescriptor_32c4df2e0eaa2354 = []byte{
	// 585 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0x51, 0x6b, 0xd4, 0x40,
	0x10, 0xc7, 0x2f, 0x97, 0xde, 0xb5, 0x99, 0xbd, 0xb6, 0xe7, 0x2a, 0x1a, 0x2a, 0xd2, 0x10, 0x04,
	0x0f, 0x84, 0x2d, 0x46, 0x85, 0x0a, 0x82, 0x68, 0x11, 0xae, 0x0f, 0xb5, 0x75, 0xb5, 0xcf, 0xc7,
	0x36, 0xb7, 0x1e, 0x8b, 0xb9, 0x4d, 0xdc, 0xdd, 0x14, 0xfa, 0xe0, 0xc7, 0xf0, 0x23, 0xf8, 0xe6,
	0xa7, 0xf0, 0x93, 0xc9, 0x6e, 0x92, 0x4b, 0xce, 0x56, 0x50, 0xf0, 0x6d, 0x66, 0xf6, 0x3f, 0x3b,
	0x33, 0xbf, 0x9d, 0x85, 0xdd, 0x94, 0x69, 0xcd, 0xe4, 0x5c, 0x31, 0x52, 0xa8, 0xdc, 0xe4, 0x7b,
	0xfb, 0x8b, 0x3c, 0x5f, 0x64, 0xfc, 0xc0, 0x79, 0x17, 0xe5, 0xa7, 0x03, 0x23, 0x96, 0x5c, 0x1b,
	0xb6, 0x2c, 0x2a, 0x41, 0xfc, 0xcd, 0x03, 0x7c, 0x2c, 0x85, 0xa1, 0xbc, 0xc8, 0x44, 0xca, 0x8e,
	0xb2, 0x52, 0x1b, 0xae, 0xf0, 0x4b, 0x40, 0x2c, 0xcb, 0x66, 0xaa, 0x8a, 0x86, 0x5e, 0xe4, 0x4f,
	0x50, 0x72, 0x9f, 0x5c, 0x57, 0x92, 0xda, 0xa5, 0xc0, 0xb2, 0xac, 0xb6, 0xf7, 0x5e, 0xc3, 0x66,
	0x6d, 0x62, 0x0c, 0x1b, 0x92, 0x2d, 0x79, 0xe8, 0x45, 0xde, 0x24, 0xa0, 0xce, 0xc6, 0x3b, 0xd0,
	0x17, 0x45, 0xd8, 0x77, 0x91, 0xbe, 0x28, 0xac, 0xa6, 0xc8, 0x95, 0x09, 0xfd, 0x4a, 0x63, 0xed,
	0xf8, 0x7b, 0x1f, 0xc6, 0x94, 0x7f, 0x29, 0xb9, 0x36, 0x67, 0x4c, 0xb1, 0x25, 0xb7, 0x5d, 0x3d,
	0x84, 0xed, 0x5c, 0x89, 0x85, 0x90, 0x74, 0xd5, 0x97, 0xcd, 0x58, 0x0f, 0xe2, 0x31, 0xf8, 0x9f,
	0xf9, 0x95, 0xbb, 0x7f, 0x9b, 0x5a, 0x13, 0xdf, 0x81, 0xc1, 0x25, 0xcb, 0x4a, 0x5e, 0x57, 0xa8,
	0x1c, 0xfc, 0x0a, 0x50, 0x9a, 0x4b, 0x2d, 0xb4, 0xe1, 0x32, 0xbd, 0x0a, 0x37, 0x22, 0x6f, 0xb2,
	0x93, 0x3c, 0x20, 0xbf, 0x57, 0x25, 0x47, 0xad, 0x88, 0x76, 0x33, 0xf0, 0x21, 0x04, 0x2b, 0x9c,
	0xe1, 0x20, 0xf2, 0x26, 0x28, 0xd9, 0x23, 0x15, 0x70, 0xd2, 0x00, 0x27, 0x1f, 0x1b, 0x05, 0x6d,
	0xc5, 0x76, 0x10, 0xeb, 0x1c, 0xcb, 0x0f, 0x3c, 0xcd, 0xe5, 0x5c, 0x87, 0xc3, 0xc8, 0x9b, 0xf8,
	0x74, 0x3d, 0x18, 0xc7, 0x80, 0x3a, 0xb5, 0xf1, 0x26, 0xf8, 0xa7, 0xef, 0xde, 0x8e, 0x7b, 0x18,
	0x60, 0xf8, 0xfe, 0xfc, 0x94, 0x9e, 0x9f, 0x8c, 0xbd, 0xf8, 0x87, 0x07, 0x5b, 0x94, 0xeb, 0x22,
	0x97, 0x9a, 0xff, 0x67, 0x3e, 0x21, 0x6c, 0x32, 0xa5, 0xc4, 0x25, 0xcb, 0x1c, 0x1b, 0x9f, 0x36,
	0x2e, 0xbe, 0x0b, 0x43, 0x6d, 0x98, 0x29, 0xb5, 0x9b, 0x7a, 0x8b, 0xd6, 0x1e, 0x8e, 0x00, 0x29,
	0xae, 0x8b, 0x13, 0xae, 0x35, 0x5b, 0x70, 0x37, 0x54, 0x40, 0xbb, 0xa1, 0xf8, 0x2b, 0xc0, 0x51,
	0x26, 0xb8, 0x34, 0x94, 0xb3, 0x79, 0xd3, 0x89, 0xd7, 0x76, 0xf2, 0x62, 0xfd, 0x4d, 0xfa, 0xee,
	0x4d, 0xee, 0x91, 0x36, 0xe7, 0x8f, 0xaf, 0xf1, 0x57, 0xb4, 0xf6, 0x01, 0x35, 0xfb, 0x7a, 0x63,
	0xfd, 0xf8, 0x19, 0x04, 0x55, 0xad, 0xb3, 0xd2, 0xe0, 0x47, 0x30, 0x10, 0xb2, 0x28, 0x8d, 0x13,
	0xa0, 0xe4, 0xd6, 0xb5, 0xd5, 0xa0, 0xd5, 0x79, 0xfc, 0x1c, 0xa0, 0xbe, 0xf6, 0x9f, 0xd2, 0x7e,
	0xf6, 0x61, 0x74, 0x6c, 0xad, 0x5a, 0x80, 0x0f, 0x61, 0x24, 0xa4, 0x30, 0x9d, 0x6f, 0x67, 0x2f,
	0xb8, 0x7d, 0xc3, 0xb7, 0x9b, 0xf6, 0x28, 0x12, 0x6d, 0x14, 0x13, 0x40, 0xa9, 0xeb, 0x7b, 0xa6,
	0x38, 0x9b, 0x3b, 0x6e, 0x28, 0x41, 0x1d, 0x6e, 0xd3, 0x1e, 0x85, 0xb4, 0x25, 0xff, 0x04, 0x46,
	0x75, 0x91, 0x2a, 0xc1, 0x77, 0x09, 0x23, 0xd2, 0xa1, 0x63, 0x4b, 0xa8, 0x0e, 0xac, 0xc7, 0x50,
	0x5f, 0x30, 0xb3, 0xb3, 0x6d, 0xb8, 0x04, 0x20, 0x2b, 0x5a, 0xd3, 0x1e, 0x0d, 0xd2, 0x15, 0x3a,
	0x02, 0x4d, 0xae, 0x53, 0x0f, 0xea, 0x7e, 0x5a, 0x4a, 0xb6, 0x1f, 0xd5, 0x65, 0xb6, 0xa5, 0xea,
	0x2d, 0x76, 0x6b, 0x83, 0x92, 0x80, 0x34, 0x6b, 0x3d, 0xed, 0xd1, 0xd5, 0xe1, 0x9b, 0x5d, 0xd8,
	0x76, 0xf0, 0x66, 0xaa, 0x62, 0x76, 0x31, 0x74, 0x3f, 0xed, 0xe9, 0xaf, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xe6, 0x64, 0xaa, 0xfd, 0xfb, 0x04, 0x00, 0x00,
}
